Student_Management/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.Index.as_view()),
    path('college/<int:pk>', views.CollegeDetail.as_view(), name='college'),
    path('college/', views.CollegeList.as_view()),
    path('create_college/', views.CollegeCreate.as_view()),
    path('create_student/', views.studentCreate.as_view()),
    path('update_college/<int:pk>', views.CollegeUpdate.as_view()),
    path('delete_student/<int:pk>', views.StudentDelete.as_view()),
]

main/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    name = models.CharField(max_length=256)
    roll_name = models.IntegerField(unique = True)
    college = models.ForeignKey('College', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class College(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from django.views.generic import (
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.views.generic.edit import UpdateView
from main import models
# Create your views here

class Index(View):
    def get(self, request):
        return HttpResponse("GET request")

    def post(self, request):
        return HttpResponse("POST response")

#GENERIC VIEWS--> Detail View for info
#List View 
#Create View 
#Update View 
#Delete View  

class CollegeDetail(DetailView):
    model=models.College  #only mandatory field, does not require meta
    template_name= 'college_detail.html'

class CollegeList(ListView):
    model = models.College
    template_name = 'college_list.html'
    context_object_name='colleges'

class CollegeCreate(CreateView):
    model = models.College
    template_name = 'college_create.html'
    fields = '__all__'
    success_url = '/college'

class studentCreate(CreateView):
    model = models.Student
    template_name = 'student_create.html'
    fields = '__all__'
    success_url = '/college'

class CollegeUpdate(UpdateView):
    model = models.College
    template_name = 'college_create.html'
    fields = '__all__'
    success_url = '/college'

class StudentDelete(DeleteView):
    model = models.Student
    template_name = 'confirm.html'
    success_url = '/college'

templates/college_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Add College</h1>

    <form action="" method="POST">
        {% csrf_token%}

        {{form}}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/college_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>College</h1>

    Name:{{ object.name }} <br>

    Students:
    <ul>
        {% for student in object.student_set.all %}
        <li>{{student.name}}</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/college_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Colleges</h1>

    <ul>
        {% for college in colleges %}
        <li>
            <a href="{% url 'college' college.pk %}">{{college.name}}</a>
        </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="">Are you sure you want to delete?</label>
        <button type="reset">NO</button>
        <button type="submit">Yes</button>
    </form>
</body>
</html>

templates/student_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Add Student</h1>

    <form action="" method="POST">
        {% csrf_token%}

        {{form}}
        <button type="submit">Submit</button>
    </form>
</body>
</html>